// <auto-generated />
using System;
using E_Commerce.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce.Infrastructure.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20231207040235_Seeding-buxanka")]
    partial class Seedingbuxanka
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("E_Commerce.Domain.Entities.Basket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("ClientTelegramId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 7, 9, 2, 35, 110, DateTimeKind.Local).AddTicks(1322),
                            Description = "Ajoyib filialimiz",
                            Latitude = 60.0,
                            Longitude = 50.0,
                            Name = "Kukcha"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 7, 9, 2, 35, 110, DateTimeKind.Local).AddTicks(1340),
                            Description = "Bu ham juda ajoyib filial",
                            Latitude = 61.0,
                            Longitude = 56.0,
                            Name = "Chilonzor"
                        });
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Choy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kabob"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Non"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shorva"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lag'mon"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Osh"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Lavash"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pitsa"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Somsa"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gazli ichimlik"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Salat"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Meva"
                        });
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastBasketProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.Feedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserTelegramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 12, 7, 9, 2, 35, 110, DateTimeKind.Local).AddTicks(2353),
                            Description = "Qimmat choy",
                            ImagePath = "https://idsb.tmgrup.com.tr/ly/uploads/images/2022/05/15/205578.jpg",
                            Name = "Turkiya choylari",
                            Price = 20000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 12, 7, 9, 2, 35, 110, DateTimeKind.Local).AddTicks(2359),
                            Description = "O'rta narxdagi choy",
                            ImagePath = "https://domf5oio6qrcr.cloudfront.net/medialibrary/8468/Tea.jpg",
                            Name = "Xitoy choylari",
                            Price = 10000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 12, 7, 9, 2, 35, 110, DateTimeKind.Local).AddTicks(2360),
                            Description = "Arzon choy",
                            ImagePath = "https://realfood.tesco.com/media/images/178-Chaispicedtea-H-efb63a82-e983-4d3c-9e3d-cb799a6f0418-0-472x310.jpg",
                            Name = "Hindiston choylari",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 12, 7, 9, 2, 35, 110, DateTimeKind.Local).AddTicks(2361),
                            Description = "Daxshat kabob",
                            ImagePath = "https://1.bp.blogspot.com/-xRoG8l4BZK8/XfasALaj1QI/AAAAAAAAPVI/RImASf05UKAvC7uwZsXsl9vERmS2W7zCwCNcBGAsYHQ/s1600/Chicken%2BKabob.JPG",
                            Name = "Tovuqli kabob",
                            Price = 13000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 12, 7, 9, 2, 35, 110, DateTimeKind.Local).AddTicks(2362),
                            Description = "Ajoyib kabob",
                            ImagePath = "https://foodiesterminal.com/wp-content/uploads/2019/11/chicken-angara-kabab-2-679x1024.jpg",
                            Name = "Go'shtli kabob",
                            Price = 15000m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 12, 7, 9, 2, 35, 110, DateTimeKind.Local).AddTicks(2364),
                            Description = "Juda shirin va mazali",
                            ImagePath = "https://api.online-bozor.uz/uploads/images/ff80818144829954794c12d7",
                            Name = "Qo'qon Patir",
                            Price = 10000m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 12, 7, 9, 2, 35, 110, DateTimeKind.Local).AddTicks(2365),
                            Description = "Juda shirin va mazali",
                            ImagePath = "https://storage.kun.uz/source/1/ssEjJUu1uNZtl84wFUwb11XwDH3wT1l0.jpg",
                            Name = "Buxanka",
                            Price = 2800m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 12, 7, 9, 2, 35, 110, DateTimeKind.Local).AddTicks(2366),
                            Description = "Juda shirin va mazali",
                            ImagePath = "https://i2.wp.com/attuale.ru/wp-content/uploads/2018/02/50270956-391b-4308-b21d-882911a30634_original.jpg",
                            Name = "Tovuq shorva",
                            Price = 18000m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 12, 7, 9, 2, 35, 110, DateTimeKind.Local).AddTicks(2367),
                            Description = "Juda shirin va mazali",
                            ImagePath = "https://www.ferganatourism.uz/d/bd72b97a.jpg",
                            Name = "Noxat shorva",
                            Price = 16000m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 12, 7, 9, 2, 35, 110, DateTimeKind.Local).AddTicks(2368),
                            Description = "Juda shirin va mazali",
                            ImagePath = "https://pazanda.com/wp-content/uploads/2017/02/img_4051.jpg",
                            Name = "Qovurma lag'mon",
                            Price = 14000m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 12, 7, 9, 2, 35, 110, DateTimeKind.Local).AddTicks(2369),
                            Description = "Juda shirin va mazali",
                            ImagePath = "https://pazanda.com/wp-content/uploads/2017/02/img_4051.jpg",
                            Name = "Choyxona palov",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 12, 7, 9, 2, 35, 110, DateTimeKind.Local).AddTicks(2370),
                            Description = "Juda shirin va mazali",
                            ImagePath = "https://pazanda.com/wp-content/uploads/2017/02/img_4051.jpg",
                            Name = "To'y oshi",
                            Price = 25000m
                        });
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.ProductList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long?>("BasketId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<long>("UserTelegramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductLists");
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.Rate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<long>("UserTelegramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.Product", b =>
                {
                    b.HasOne("E_Commerce.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.ProductList", b =>
                {
                    b.HasOne("E_Commerce.Domain.Entities.Basket", null)
                        .WithMany("Products")
                        .HasForeignKey("BasketId");

                    b.HasOne("E_Commerce.Domain.Entities.Order", null)
                        .WithMany("ProductList")
                        .HasForeignKey("OrderId");

                    b.HasOne("E_Commerce.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.Basket", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_Commerce.Domain.Entities.Order", b =>
                {
                    b.Navigation("ProductList");
                });
#pragma warning restore 612, 618
        }
    }
}
